config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/user', to: 'static_pages#user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    direction = (1..4).to_a.shuffle.first
    @s_dir = ""
    if direction == 1
      @s_dir = "North"
    elsif direction == 2
      @s_dir = "West"
    elsif direction == 3
      @s_dir = "East"
    else
      @s_dir = "South"
    end
  end

  def about
  end

  def user
  end
end

app/helpers/application_helper.rb
#Referenced Hartl Textbook
#Referenced Dice Roller Practice by Tristan
module ApplicationHelper
  def full_title(page_title = '')
  base_title = "Direct Adventures"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div><h1><%= yield(:title) %></h1></div>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "User", user_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track':
        'reload' %>
    <%= render 'layouts/shim' %>   
  </head>

  <body>
    <%= render 'layouts/header'%>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>

<html>
  <head>
    <title><%= yield(:title) %> | Direct Adventures</title>
  </head>
  <body>
    <h1>About</h1>
    <p>Created by Aidan Danbury, Direct Adventures is an app meant to
      showcase by abilities as a software developer. Its intended goal
      is to act as a choose-your-own-adventure app in which users may
      log in, add pages, and create links to existing pages in order to
      create long, complex, and perhaps collaborative narratives. While
      as of 5/15/2020 it has not achieved some of these functionalities,
      the website does have a compelling home page. A user, upon arriving
      at the website, is confronted with the question "Where do you want
      to go?", with "The Wind" giving a randomized suggestion. The cardinal
      directions are meant to navigate different areas of the site, each
      suggesting different ways to navigate and interact with Direct
      Adventures. Hopefully, these ideas may be improved upon in the
      future.</p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>

<html>
  <head>
    <title><%= yield(:title) %></title>
  </head>
  <body>
    <div class="onleft"><br><br><br>The West</div>
    <div class="onright"><br><br><br>The East</div>
    <div class="center">
      The North<br><br><br>
      Where do you want to go?<br>
      <p>The Wind Blows <%= @s_dir %></p><br><br>
      The South</div>
  </body>
</html>

app/views/static_pages/user.html.erb
<% provide(:title, "User") %>
<!DOCTYPE html>

<html>
  <head>
    <title><%= yield(:title) %> | Direct Adventures</title>
  </head>
  <body>
    <h1>User</h1>
    <p>Log in functionality currently unavailable</p>
  </body>
  
</html>